name: Docker Build

on:
  push:
    branches:
      - production

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install quemu emulators
        run: |
          docker run -td --rm --privileged tonistiigi/binfmt --install all

      - name: Checkout Repository 👀
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          
      - name: Build and Push Docker Image 🐋
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t $DOCKER_USERNAME/$REPO_NAME:latest -f server/Dockerfile . --push
